### ISSUE TITLE
nevent links are broken

### ISSUE THREAD

**Issue by mikedilger** [frnandu/yana#60]
A user of yana has included this link in their note:

nostr:nevent1qqswrqr63ddwk8l3zfqrgdxh2lxh2jlcxl36k3h33g25gtchzchx8agpp4mhxue69uhkummn9ekx7mqpz3mhxue69uhhyetvv9ujuerpd46hxtnfduq3yamnwvaz7tm0venxx6rpd9hzuur4vgpyqdmyxs6rzdmyx4jxvdpnx4snjdmz8pnr2dtr8pnryefhv5ex2e34xvek2v3nxuckxef4v5ckxenxvs6njdtrxymnjcfnv4skvvekvs6qfe99uy

This link's 'author' field is not 32 binary bytes of a pubkey, but 64 bytes (presumably of the hex-encoded pubkey).

I've updated my client to tolerate this, but I thought you might want to fix it.

**Comment by frnandu** [comment]
Thanks mike for reporting, fix is in 0.14.2 release
