### ISSUE TITLE
Many profiles do not parse the name/identifier(nip05), just pure npub

### ISSUE THREAD

**Issue by itstomekk** [frnandu/yana#86]
I guess Yana could check some nostr.band or purplepages relay for its name? Raw npubs do not look bad

![image](https://github.com/user-attachments/assets/ef73cbde-4f52-4f20-a940-c50a6fc05274)

**Comment by frnandu** [comment]
this should be fixed now, it still takes some delay to fetch unknown profiles metadata in global, but it should fetch them eventually
